### PR TITLE
Swift 4

### PR DESCRIPTION
**Pull request by ksmandersen**
- Added full support for Swift 4.0
- Fixed a bunch of warnings
- Updated to recommended project settings

### CODE REVIEW

**Comment by madhavajay** [comment]
Let me take a quick look. 👍

**Comment by ksmandersen** [comment]
@madhavajay Let's wait until the travis build completes. Had to tweak some things, because swiftlint makes it fail

**Comment by elm4ward** [comment]
Wow - @ksmandersen Thank you very much.
I was planning to make an update and basically boil it down to `Codable`.
But your PR is already very welcome!

👍🙏🎊

**Comment by ksmandersen** [comment]
Now swiftlint works on travis but the tests fail. Not sure what is up with that. They all pass locally. Anyone got some insight?

**Comment by madhavajay** [comment]
@ksmandersen its going to be the simulator versions, its a total pain every time they change. I would actually suggest changing this to use fastlane.

First would be to create a fastfile using fastlane, then to invoke that in the travis file.

**Comment by ksmandersen** [comment]
@madhavajay That seems like a separate concern from simply supporting Swift4/Xcode9. I also haven't used fastlane before, so am not familiar with how it works. 

I've updated the simulator versions. So let's see if that doesn't work for now

**Comment by madhavajay** [comment]
@ksmandersen yeah if updating the simulators works thats fine for now. 👍

For your own sake, please go checkout fastlane like right now.
It will blow your mind and rock your iOS world.
Seriously, its like.... the missing toolchain for iOS dev. 😎

**Comment by ksmandersen** [comment]
Looks like the tests will pass now

**Comment by madhavajay** [comment]
I think its just the watch device build failing now due to incorrect device name. Really annoying that Xcode does this.

Also can you please bump the version to say: 1.0.4 in the plist files?

**Comment by ksmandersen** [comment]
@madhavajay Let's try that again.

Bumped to version 1.0.4 now

**Comment by madhavajay** [comment]
@ksmandersen I just made a PR to your fork from my fork with the new fastlane and travis changes. Can you merge that and then it should get added to this PR.

**Comment by ksmandersen** [comment]
@madhavajay Done

**Comment by elm4ward** [comment]
cool

**Comment by madhavajay** [comment]
Woohoo. 🎉 Good job everyone! 👍

**Pull request merged**
