### PR TITLE
Reuse of NSUserDefaults typealias in UserDefaultsEntry

### PR DESCRIPTION
**Pull request by fuxx**
NSUD == NSUserDefaults

### CODE REVIEW

**Comment by fuxx** [comment]
Sorry, i thought the request will be merged with #2. Its not a duplicate.

**Comment by madhavajay** [comment]
We had to rename the class files can you please pull rebase and re push your changes on the latest master?

**Comment by fuxx** [comment]
sure, tomorrow :)

**Comment by elm4ward** [comment]
ty!

**Pull request merged**
